version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:${PORT}'
    volumes:
      - .:/app
    networks:
      - app-net
    env_file:
      - .env
    command: ["pnpm", "run","start:dev"]
  
networks:
  app-net: